### ISSUE TITLE
Crash in main() on startup on Windows 10

### ISSUE THREAD

**Issue by allisterb** [Microsoft/R-Host#160]
I followed the build instructions and was able to build it successfully on VS 2017, but running Microsoft.R.Host.exe gives this error:

![foo](https://ph59pw.dm.files.1drv.com/y4m5R8-tD7yAlXf4RDmrVfGZH4FIPW_2wPLOjqx8FCIa1kwaqSy6WyckQQWmbm86S_lv9ax8Y4anT7GOhFVYrvyKTCIln9ZkzzxIc8zfQ-T89QKMz3tR-qr2uCPjjV2debLUtS56M4N8t-qXORJ5Jkp4NcaoFDz34mpzNnBHjUGiloh2HcelVg75wBpCn8zCVaygoEAJp65lBnVB3krPGJJnw?width=1920&height=1080&cropmode=none)

**Comment by karthiknadig** [comment]
Did you just Run R-Host by itself or Run it via https://github.com/Microsoft/RTVS? There are a few required parameters and environment variables to run R-Host.

Try this and let me know:
Environment:
* `R_HOME = <set this to interpreter install path>` like `C:\Program Files\R\R-3.4.3`
* `PATH = <Set this to interpreter path>` like `C:\Program Files\R\R-3.4.3\bin\x64`

Then run this Command line:
`Microsoft.R.Host.exe --rhost-r-dir "C:\Program Files\R\R-3.4.3" --rhost-name "ManualLaunch" --rhost-log-verbosity 3`

You should be able the see the logs in Temp directory. They should have the prefix given in `--rhost-name`

**Comment by allisterb** [comment]
Awesome, I was able to get it to work. Thank you!
