### ISSUE TITLE
Visual studio 2017 c++ solution

### ISSUE THREAD

**Issue by vivanov879** [Microsoft/R-Host#163]
Hi Mikhail. Downloaded the solution in src/ but couldnt build a dll with it. Would you provide a ready to use visual studio 2017 solution where i would just fill the correct linking and header paths and build it. And either build dll for later use or work right in the solution. Probably im not that good at visual studion. I can build simple solutions but not this one. Thanks.

**Comment by MikhailArkhipov** [comment]
You need MSys32 to build it using gcc. Please follow build steps in the RHost repo.

**Comment by vivanov879** [comment]
I see -- thanks
